import { Injectable } from '@angular/core';
import { Product } from '../product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  products: Product[] = [
    {
      id: 1,
      name: 'Produto 1',
      description: 'Este é o produto 1',
      price: "100,00",
      image:"/assets/cesta1.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],
      images:["/assets/cesta1.jpeg", "/assets/cesta1.jpeg", "/assets/cesta1.jpeg"],
    },
    {
      id: 2,
      name: 'Produto 2',
      description: 'Este é o produto 2',
      price: "200,00",
      image:"/assets/cesta2.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],
      images:["/assets/cesta2.jpeg", "/assets/cesta2.jpeg", "/assets/cesta2.jpeg"],
    },
    {
      id: 3,
      name: 'Produto 3',
      description: 'Este é o produto 3',
      price: "300,00",
      image:"/assets/cesta3.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],
      images:["/assets/cesta3.jpeg", "/assets/cesta3.jpeg", "/assets/cesta3.jpeg"],
    },

    {
      id: 4,
      name: 'Produto 4',
      description: 'Este é o produto 4',
      price: "400,00",
      image:"/assets/cesta1.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],
      images:["/assets/cesta1.jpeg", "/assets/cesta1.jpeg", "/assets/cesta1.jpeg"],
    },
    {
      id: 5,
      name: 'Produto 5',
      description: 'Este é o produto 5',
      price: "500,00",
      image:"/assets/cesta2.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],      images:["/assets/cesta2.jpeg", "/assets/cesta2.jpeg", "/assets/cesta2.jpeg"],
    },
    {
      id: 6,
      name: 'Produto 6',
      description: 'Este é o produto 6',
      price: "600,00",
      image:"/assets/cesta3.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],      images:["/assets/cesta3.jpeg", "/assets/cesta3.jpeg", "/assets/cesta3.jpeg"],
    },
    {
      id: 7,
      name: 'Produto 7',
      description: 'Este é o produto 7',
      price: "700,00",
      image:"/assets/cesta1.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],      images:["/assets/cesta1.jpeg", "/assets/cesta1.jpeg", "/assets/cesta1.jpeg"],
    },
    {
      id: 8,
      name: 'Produto 8',
      description: 'Este é o produto 8',
      price: "800,00",
      image:"/assets/cesta2.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],
      images:["/assets/cesta2.jpeg", "/assets/cesta2.jpeg", "/assets/cesta2.jpeg"],
    },
    {
      id: 9,
      name: 'Produto 9',
      price: "900,00",
      description: 'Servindo três pessoas, a cesta especial é composta por uma refeição completa. Mais do que se surpreender, é possível começar o dia com ainda mais alegria e disposição. Perfeito para agradar a sua família em momentos especiais!',
      image:"/assets/cesta3.jpeg",
      items:["Mini bolo caseiro,",
      "Croissant Recheado,",
       "Mini pães,",
       "1 Waffle,",
       "Polenguinho,",
       "Geleia de Morango (Porção),",
        "Pães de queijo,",
         "Quiche de queijo e bacon,",
         "Torradinhas,",
         "1 Suco de uva,",
         "1 Fruta,",
         "1 Vasinho de suculenta,",
         "1 Caixote de madeira,",
         "2 Fotos*."],
      images:["/assets/cesta2.jpeg", "/assets/cesta3.jpeg", "/assets/cesta1.jpeg"],
    },
    {
      id: 10,
      name: 'Produto 10',
      description: 'Este é o produto 10',
      price: "1000,00",
      image:"/assets/cesta1.jpeg",
      items:["Mini bolo caseiro (sabor do dia),",
      "Croissant Recheado,",
      "Mini pães",
      "1 Waffle",
      "Polenguinho",
      "Geleia de Morango (Porção)",
      "Pães de queijo",
      "Quiche de queijo",
      "Torradinhas",
      "1 Suco de uva  250 ml",
      "1 Fruta",
      "1 Vasinho de suculenta,",
      "1 Caixote de madeira,",
      "2 Fotos"],
      images:["/assets/cesta1.jpeg", "/assets/cesta1.jpeg", "/assets/cesta1.jpeg"],
    },

  ];

  constructor() { }


  getProdutos(): Product[] {
    return this.products;
  }

  getProdutoById(id: number): Product {
    return this.products.find((produto) => produto.id === id)!;
  }

}
